### ISSUE TITLE
Error during module start due to undefined property

### ISSUE THREAD

**Issue by skastenholz** [skastenholz/MMM-DVB#10]
Since merging #8  the following ERROR arises during module start:

> [ERROR] Whoops! There was an uncaught exception...
> [ERROR] TypeError: Cannot read properties of undefined (reading 'id')
>     at Class.socketNotificationReceived (/opt/magic_mirror/modules/MMM-DVB/node_helper.js:43:44)
>     at Socket.<anonymous> (/opt/magic_mirror/js/node_helper.js:108:11)
>     at Socket.emit (node:events:513:28)
>     at Socket.emitUntyped (/opt/magic_mirror/node_modules/socket.io/dist/typed-events.js:69:22)
>     at /opt/magic_mirror/node_modules/socket.io/dist/socket.js:475:39
>     at processTicksAndRejections (node:internal/process/task_queues:78:11)

@VDenisyuk Can you please analyze and fix the same? Thx

**Comment by VDenisyuk** [comment]
I just did a clean install from the `main` branch now and performed testing with 4 modules (every module has a different stop to monitor). So far I have not experienced any errors, but I will keep an eye on it.
What was your reproducibility rate? Was it occasionally, often, or always?
